<?php
/**
 * AntifraudApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Conekta
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Conekta API
 *
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@conekta.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Conekta\Test\Api;

use \Conekta\Configuration;
use \Conekta\ApiException;
use \Conekta\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AntifraudApiTest Class Doc Comment
 *
 * @category Class
 * @package  Conekta
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AntifraudApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createRuleBlacklist
     *
     * Create blacklisted rule.
     *
     */
    public function testCreateRuleBlacklist()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createRuleWhitelist
     *
     * Create whitelisted rule.
     *
     */
    public function testCreateRuleWhitelist()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteRuleBlacklist
     *
     * Delete blacklisted rule.
     *
     */
    public function testDeleteRuleBlacklist()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteRuleWhitelist
     *
     * Delete whitelisted rule.
     *
     */
    public function testDeleteRuleWhitelist()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getRuleBlacklist
     *
     * Get list of blacklisted rules.
     *
     */
    public function testGetRuleBlacklist()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getRuleWhitelist
     *
     * Get a list of whitelisted rules.
     *
     */
    public function testGetRuleWhitelist()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
