<?php
/**
 * ProductsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Conekta
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Conekta API
 *
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@conekta.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Conekta\Test\Api;

use Conekta\Api\ProductsApi;
use \Conekta\Configuration;
use \Conekta\ApiException;
use Conekta\Model\Product;
use Conekta\Model\UpdateProduct;
use \Conekta\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ProductsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Conekta
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProductsApiTest extends TestCase
{

    protected static ProductsApi $apiInstance;

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
        $config = Configuration::getDefaultConfiguration()->setHost(BaseTest::$host);
        self::$apiInstance = new ProductsApi(null, $config);
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for ordersCreateProduct
     *
     * Create Product.
     *
     */
    public function testOrdersCreateProduct()
    {
        $accept_language = 'es';
        $rq = new Product([
            'name' => 'test'
        ]);
        $result = self::$apiInstance->ordersCreateProduct('id', $rq, $accept_language);
        $this->assertNotEmpty($result, 'expected not empty result');
    }

    /**
     * Test case for ordersDeleteProduct
     *
     * Delete Product.
     *
     */
    public function testOrdersDeleteProduct()
    {
        $accept_language = 'es';
        $result = self::$apiInstance->ordersDeleteProduct('id', 'id', $accept_language);
        $this->assertNotEmpty($result, 'expected not empty result');
    }

    /**
     * Test case for ordersUpdateProduct
     *
     * Update Product.
     *
     */
    public function testOrdersUpdateProduct()
    {
        $accept_language = 'es';
        $rq = new UpdateProduct([
            'name' => 'test'
        ]);
        $result = self::$apiInstance->ordersUpdateProduct('id', 'id', $rq, $accept_language);
        $this->assertNotEmpty($result, 'expected not empty result');
    }
}
