<?php
/**
 * ShippingContactsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Conekta
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Conekta API
 *
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@conekta.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Conekta\Test\Api;

use Conekta\Api\ShippingContactsApi;
use \Conekta\Configuration;
use \Conekta\ApiException;
use Conekta\Model\CustomerShippingContacts;
use Conekta\Model\CustomerUpdateShippingContacts;
use \Conekta\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ShippingContactsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Conekta
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ShippingContactsApiTest extends TestCase
{

    protected static ShippingContactsApi $apiInstance;

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
        $config = Configuration::getDefaultConfiguration()->setHost(BaseTest::$host);
        self::$apiInstance = new ShippingContactsApi(null, $config);
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createCustomerShippingContacts
     *
     * Create a shipping contacts.
     *
     */
    public function testCreateCustomerShippingContacts()
    {
        $accept_language = 'es';
        $rq = new CustomerShippingContacts([
            'phone' => '55555555'
        ]);
        $result = self::$apiInstance->createCustomerShippingContacts('id', $rq, $accept_language);
        $this->assertNotEmpty($result, 'expected not empty result');
    }

    /**
     * Test case for deleteCustomerShippingContacts
     *
     * Delete shipping contacts.
     *
     */
    public function testDeleteCustomerShippingContacts()
    {
        $accept_language = 'es';
        $result = self::$apiInstance->deleteCustomerShippingContacts('id', 'id', $accept_language);
        $this->assertNotEmpty($result, 'expected not empty result');
    }

    /**
     * Test case for updateCustomerShippingContacts
     *
     * Update shipping contacts.
     *
     */
    public function testUpdateCustomerShippingContacts()
    {
        $accept_language = 'es';
        $rq = new CustomerUpdateShippingContacts([
            'amount' => 1000
        ]);
        $result = self::$apiInstance->updateCustomerShippingContacts('id', 'id', $rq, $accept_language);
        $this->assertNotEmpty($result, 'expected not empty result');
    }
}
