<?php
/**
 * WebhookKeysApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Conekta
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Conekta API
 *
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@conekta.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Conekta\Test\Api;

use \Conekta\Configuration;
use \Conekta\ApiException;
use \Conekta\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * WebhookKeysApiTest Class Doc Comment
 *
 * @category Class
 * @package  Conekta
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WebhookKeysApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createWebhookKey
     *
     * Create Webhook Key.
     *
     */
    public function testCreateWebhookKey()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteWebhookKey
     *
     * Delete Webhook key.
     *
     */
    public function testDeleteWebhookKey()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getWebhookKey
     *
     * Get Webhook Key.
     *
     */
    public function testGetWebhookKey()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getWebhookKeys
     *
     * Get List of Webhook Keys.
     *
     */
    public function testGetWebhookKeys()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateWebhookKey
     *
     * Update Webhook Key.
     *
     */
    public function testUpdateWebhookKey()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
